[package]
name = "neural_networks"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
ndarray = { version = "0.16.0" }
ndarray-rand = "0.15.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "train_benchmark"
harness = false
